import java.util.regex.Pattern
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This build file was auto generated by running the Gradle 'init' task
 * by 'Juergen' at '22.06.14 22:50' with Gradle 1.11
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at http://gradle.org/docs/1.11/userguide/tutorial_java_projects.html
 */

// Apply the java plugin to add support for Java
plugins {
    id("java")
    id("eclipse")
    id("idea")
    id("maven-publish")
    kotlin("jvm") version Versions.kotlinVersion
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_6
    targetCompatibility = JavaVersion.VERSION_1_6
}
group = "com.github.movisens"
val packageJsonVersionRegex = Pattern.compile("\"version\":").toRegex()
version = rootProject.file("package.json")
    .bufferedReader()
    .readLines()
    .firstOrNull { packageJsonVersionRegex.find(it) != null }
    ?.replace(packageJsonVersionRegex, "")
    ?.replace(Regex("[\",]"), "")
    ?.trim() ?: "1.0.0"

// In this section you declare where to find the dependencies of your project
repositories {
    // Use 'maven central' for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
    jcenter()
}

// In this section you declare the dependencies for your production and test code
dependencies {
    // The production code
    implementation("com.squareup.retrofit2:retrofit:${Versions.retrofitVersion}")
    implementation("com.squareup.retrofit2:converter-gson:${Versions.retrofitVersion}")
    implementation("com.squareup.okhttp3:logging-interceptor:3.4.1")
    compileOnly("org.jetbrains:annotations:17.0.0")

    // Declare the dependency for your favourite test framework you want to use in your tests.
    // TestNG is also supported by the Gradle Test task. Just change the
    // testCompile dependency to testCompile 'org.testng:testng:6.8.1' and add
    // "test.useTestNG()' to your build script.
    testImplementation("junit:junit:4.11")
    testImplementation("com.jayway.awaitility:awaitility:1.7.0")
    testImplementation("commons-io:commons-io:2.6")
    implementation(kotlin("stdlib-jdk8"))
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.6"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.6"
}