package com.movisens.xs.api.test

import com.movisens.xs.api.XSApi
import com.movisens.xs.api.XSService
import com.movisens.xs.api.exceptions.AuthorizationException
import com.movisens.xs.api.models.Study
import org.junit.Assert
import org.junit.Test

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Juergen' at '22.06.14 22:50' with Gradle 1.11
 *
 * @author Juergen, @date 22.06.14 22:50
 */
class AuthorizationTest {
    var service = XSApi.Builder(API_KEY).setServer(SERVER_URL).build().create(
        XSService::class.java
    )

    @Test
    fun testGetStudy() {
        var ex: Exception? = null
        var study: Study? = null
        try {
            val call = service.getStudy(989)
            study = call.execute().body()
        } catch (e: Exception) {
            ex = e
        }
        Assert.assertEquals("getStudy should be null", null, study)
        Assert.assertEquals(
            "getStudy should throw UnauthorizedException when wrong key is supplied",
            true, ex is AuthorizationException
        )
    }

    companion object {
        private const val SERVER_URL = "https://xs.movisens.com"
        private const val API_KEY = "WRONG KEY"
    }
}