package com.movisens.xs.api.test;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import com.movisens.xs.api.XSApi;
import com.movisens.xs.api.XSService;
import com.movisens.xs.api.exceptions.NotFoundException;
import com.movisens.xs.api.models.Study;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Juergen' at '22.06.14 22:50' with Gradle 1.11
 *
 * @author Juergen, @date 22.06.14 22:50
 */
public class StudyNotFoundTest {
	private static final String SERVER_URL = "https://hoc-hc013.hoc.uni-karlsruhe.de";
	private static final String API_KEY = "e4prtw8zcmw3a4evuesyjvzmfdfop25hl9zq9h2p";

	XSService service = new XSApi.Builder(API_KEY).setServer(SERVER_URL).build().create(XSService.class);

	@Test
	public void testGetStudy() {
		Exception ex = null;
		Study study = null;
		try {
			study = service.getStudy(9999999).execute().body();
		} catch (Exception e) {
			e.printStackTrace();
			ex = e;
		}
		assertEquals("getStudy should be null", null, study);
		assertEquals("Exception should be NotFoundException", ex instanceof NotFoundException, true);
	}
}
