package com.movisens.xs.api.test

import com.movisens.xs.api.XSApi
import com.movisens.xs.api.XSService
import com.movisens.xs.api.exceptions.NotFoundException
import com.movisens.xs.api.models.Study
import org.junit.Assert
import org.junit.Test

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Juergen' at '22.06.14 22:50' with Gradle 1.11
 *
 * @author Juergen, @date 22.06.14 22:50
 */
class StudyNotFoundTest {
    var service = XSApi.Builder(API_KEY).setServer(SERVER_URL).build().create(
        XSService::class.java
    )

    @Test
    fun testGetStudy() {
        var ex: Exception? = null
        var study: Study? = null
        try {
            study = service.getStudy(9999999).execute().body()
        } catch (e: Exception) {
            ex = e
        }
        Assert.assertEquals("getStudy should be null", null, study)
        Assert.assertEquals("Exception should be NotFoundException", true, ex is NotFoundException)
    }

    companion object {
        private const val SERVER_URL = "https://xs.movisens.com"
        private const val API_KEY = "e4prtw8zcmw3a4evuesyjvzmfdfop25hl9zq9h2p"
    }
}